language: python
env:
before_install:
- sudo apt-get install python-dev
- sudo apt-get install g++
install:
- pip install boto
- pip install wheel
- pip wheel --wheel-dir=wheelhouse cython
- pip wheel --wheel-dir=wheelhouse pandas
- pip wheel --wheel-dir=wheelhouse zerorpc
script:
- echo 'Wheels are Finished...'
- echo 'Creating Tar File...'
- tar cvfz wheelhouse/wheelhouse.tar.gz wheelhouse/*
- echo 'Removing Wheels...'
- rm wheelhouse/*.whl
deploy:
  provider: s3
  access_key_id: AKIAI7GWEYB3D2J2WWNQ
  secret_access_key:
    secure: P+kiJCdMgEL9IWcXCRbniOlRBS4mqaMmbPRBWfGF1c8bxpoO0YJnlwEsdiEpER+eQTuTdps29WN63FuN6eaALtLkIJ3DIzkp+TiqYHVm1RoypS7PTD6NbKau0cJa4eveEpW1PdLpRSlETUhFqBcA8TLRI6ud4trnKNWvmDEJEHU=
  bucket: workbench-wheels
  local-dir: wheelhouse
  skip_cleanup: true
  acl: public_read
  on:
    repo: SuperCowPowers/travis-wheels
